name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # GitHub Pages'ni qaysi tarmoqdan joylashtirishni xohlasangiz, o'shani tanlang

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
